In [1]:
print("Hi! My name is Vishnu.M")

Hi! My name is Vishnu.M


In [2]:
print("Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.!!")

Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.!!


In [85]:
#print a electronic cake
print("\t\t\t\t    @@@@\n")
print("\t\t\t\t   {    }\n")
print("\t\t\t\t  @@@@@@@\n")
print("\t\t\t\t  {      }\n")
print("\t\t\t\t @@@@@@@@@@@\n")
print("\t\t\t\t{           }")


				    @@@@

				   {    }

				  @@@@@@@

				  {      }

				 @@@@@@@@@@@

				{           }


In [93]:
#shape shifters
your_cloud_shapes=['circle','turtle','dolphin','truck','apple','spoon']
friend_cloud_shapes=['apple','turtle','spoon','truck','circle','dolphin']
if your_cloud_shapes[0]==friend_cloud_shapes[0]:
    print("we saw the same shape!")
elif your_cloud_shapes[0]!=friend_cloud_shapes[0]:
    print("we saw different shape this time!")
if your_cloud_shapes[1]==friend_cloud_shapes[1]:
    print("we saw the same shape")
elif your_cloud_shapes[1]!=friend_cloud_shapes[1]:
    print("we saw different shape this time!")
if your_cloud_shapes[2]==friend_cloud_shapes[2]:
    print("we saw the same shape")
elif your_cloud_shapes[2]!=friend_cloud_shapes[2]:
    print("we saw different shape this time!") 
if your_cloud_shapes[3]==friend_cloud_shapes[3]:
    print("we saw the same shape")
elif your_cloud_shapes[3]!=friend_cloud_shapes[3]:
    print("we saw different shape this time!")
if your_cloud_shapes[4]==friend_cloud_shapes[4]:
    print("we saw the same shape")
elif your_cloud_shapes[4]!=friend_cloud_shapes[4]:
    print("we saw different shape this time!")
if your_cloud_shapes[5]==friend_cloud_shapes[5]:
    print("we saw the same shape")
elif your_cloud_shapes[5]!=friend_cloud_shapes[5]:
    print("we saw different shape this time!")   

we saw different shape this time!
we saw the same shape
we saw different shape this time!
we saw the same shape
we saw different shape this time!
we saw different shape this time!


In [106]:
#solution for collection 1
person=['Adrienne','Tacke','Brown','Black',10,10]
print(f"{person} is srored in a list")
Animals=['dogs','cats','turtle','bunnies']
print(f"{Animals} is stored in list")
rainbow=("orange","yellow","green","blue","indigo","violet")
print(f"{rainbow} is stored in tuple")

['Adrienne', 'Tacke', 'Brown', 'Black', 10, 10] is srored in a list
['dogs', 'cats', 'turtle', 'bunnies'] is stored in list
('orange', 'yellow', 'green', 'blue', 'indigo', 'violet') is stored in tuple


In [115]:
#checking numpy version
import numpy as np
print(np.version.version)


1.20.1


In [116]:
#1D array from 0 to 9
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [118]:
#creating array filled with zeros
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
#creating array with evenly spaced numbers
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [122]:
#sorting elements in ascending order
arr=np.array([2,1,5,3,7,4,6,8])
np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
#extracting odd numbers from array
a = np.array([1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [129]:
#converting 1D array to 2D array
A = np.array([1,2,3,4,5,6])
B = np.reshape(A, (-1, 2))
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [130]:
#printing unique values
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values=np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [133]:
# reversing 1D array
arr=np.array([1,2,3,4,5,6,7,8])
np.flip(arr)


array([8, 7, 6, 5, 4, 3, 2, 1])

In [137]:
#using for loop measuring the length of each word in the list
def findLen(list):
    counter = 0    
    for i in list:
        counter += 1
    return counter
  
  
list=['cat','window','defenstrate']
print(findLen(str[0]))
print(findLen(str[1]))
print(findLen(str[2]))

3
6
11


In [143]:
#using for loop and range function iterate over the indices of a list

if __name__ == '__main__':
 
    chars = ['mary','had','a','little','lamp']
 
    for i in range(len(chars)):
        print((i, chars[i]))
 

(0, 'mary')
(1, 'had')
(2, 'a')
(3, 'little')
(4, 'lamp')


In [145]:
#pandas titanic dataset
import pandas as pd
titanic=pd.read_csv("titanic_lyst7308.csv")
#printing first 10 rows
titanic.head(10)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

     age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.00      0      0     24160  211.3375       B5        S    2    NaN   
1   0.92      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.00      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.00      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.00      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.00      0      0     19952   26.5500      E12        S    3    NaN   
6  63.00      1      0     13502   77.9583       D7        S   10    NaN   
7  39.00      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.00      2      0     11769   51.4792     C101        S    D    NaN   
9  71.00      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay

In [146]:
#printing last 10 rows
titanic.tail(10)

pclass  survived                                     name     sex   age  \
1299       3         0                      Yasbeck, Mr. Antoni    male  27.0   
1300       3         1  Yasbeck, Mrs. Antoni (Selini Alexander)  female  15.0   
1301       3         0                     Youseff, Mr. Gerious    male  45.5   
1302       3         0                        Yousif, Mr. Wazli    male   NaN   
1303       3         0                    Yousseff, Mr. Gerious    male   NaN   
1304       3         0                     Zabour, Miss. Hileni  female  14.5   
1305       3         0                    Zabour, Miss. Thamine  female   NaN   
1306       3         0                Zakarian, Mr. Mapriededer    male  26.5   
1307       3         0                      Zakarian, Mr. Ortin    male  27.0   
1308       3         0                       Zimmerman, Mr. Leo    male  29.0   

      sibsp  parch  ticket     fare cabin embarked boat   body home.dest  
1299      1      0    2659  14.4542   NaN        C    C    NaN       NaN  
1300      1      0    2659  14.4542   NaN        C  NaN    NaN       NaN  
1301      0      0    2628   7.2250   NaN        C  NaN  312.0       NaN  
1302      0      0    2647   7.2250   NaN        C  NaN    NaN       NaN  
1303      0      0    2627  14.4583   NaN        C  NaN    NaN       NaN  
1304      1      0    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305      1      0    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306      0      0    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307      0      0    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308      0      0  315082   7.8750   NaN        S  NaN    NaN       NaN

In [147]:
#filtering passengers older than 25
above_25=titanic[titanic["age"]>25]
above_25.head(10)

pclass  survived                                           name     sex  \
0        1         1                  Allen, Miss. Elisabeth Walton  female   
3        1         0           Allison, Mr. Hudson Joshua Creighton    male   
5        1         1                            Anderson, Mr. Harry    male   
6        1         1              Andrews, Miss. Kornelia Theodosia  female   
7        1         0                         Andrews, Mr. Thomas Jr    male   
8        1         1  Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9        1         0                        Artagaveytia, Mr. Ramon    male   
10       1         0                         Astor, Col. John Jacob    male   
13       1         1                   Barber, Miss. Ellen "Nellie"  female   
14       1         1           Barkworth, Mr. Algernon Henry Wilson    male   

     age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0   29.0      0      0     24160  211.3375       B5        S    2    NaN   
3   30.0      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
5   48.0      0      0     19952   26.5500      E12        S    3    NaN   
6   63.0      1      0     13502   77.9583       D7        S   10    NaN   
7   39.0      0      0    112050    0.0000      A36        S  NaN    NaN   
8   53.0      2      0     11769   51.4792     C101        S    D    NaN   
9   71.0      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   
10  47.0      1      0  PC 17757  227.5250  C62 C64        C  NaN  124.0   
13  26.0      0      0     19877   78.8500      NaN        S    6    NaN   
14  80.0      0      0     27042   30.0000      A23        S    B    NaN   

                          home.dest  
0                      St Louis, MO  
3   Montreal, PQ / Chesterville, ON  
5                      New York, NY  
6                        Hudson, NY  
7                       Belfast, NI  
8               Bayside, Queens, NY  
9               Montevideo, Uruguay  
10                     New York, NY  
13                              NaN  
14                    Hessle, Yorks

In [148]:
#selecting the name of passengers older the 35 
passengers_name=titanic.loc[titanic["age"]>35,"name"]
passengers_name.head(8)

5                                 Anderson, Mr. Harry
6                   Andrews, Miss. Kornelia Theodosia
7                              Andrews, Mr. Thomas Jr
8       Appleton, Mrs. Edward Dale (Charlotte Lamson)
9                             Artagaveytia, Mr. Ramon
10                             Astor, Col. John Jacob
14               Barkworth, Mr. Algernon Henry Wilson
17    Baxter, Mrs. James (Helene DeLaudeniere Chaput)
Name: name, dtype: object

In [149]:
#median age and ticket fare of passengers
titanic[["age","fare"]].median()

age     28.0000
fare    14.4542
dtype: float64

In [150]:
#min,max and mean of age and fare of passengers using.agg()method
titanic.agg({"age":['min','max','mean'],"fare":['min','max','mean']})

age        fare
min    0.170000    0.000000
max   80.000000  512.329200
mean  29.881138   33.295479

In [155]:
#mean ticket fare price foreach sex and cabin class combination
titanic.groupby(["sex","pclass"])["fare"].mean()

sex     pclass
female  1         109.412385
        2          23.234827
        3          15.324250
male    1          69.888385
        2          19.904946
        3          12.415462
Name: fare, dtype: float64

In [156]:
#sorting titanic data according to age of passengers
titanic.sort_values(by="age").head(10)

pclass  survived                                     name     sex   age  \
763        3         1  Dean, Miss. Elizabeth Gladys "Millvina"  female  0.17   
747        3         0  Danbom, Master. Gilbert Sigvard Emanuel    male  0.33   
1240       3         1          Thomas, Master. Assad Alexander    male  0.42   
427        2         1                Hamalainen, Master. Viljo    male  0.67   
1111       3         0           Peacock, Master. Alfred Edward    male  0.75   
657        3         1                   Baclini, Miss. Eugenie  female  0.75   
658        3         1            Baclini, Miss. Helene Barbara  female  0.75   
359        2         1            Caldwell, Master. Alden Gates    male  0.83   
611        3         1                Aks, Master. Philip Frank    male  0.83   
548        2         1          Richards, Master. George Sibley    male  0.83   

      sibsp  parch              ticket     fare cabin embarked boat  body  \
763       1      2           C.A. 2315  20.5750   NaN        S   10   NaN   
747       0      2              347080  14.4000   NaN        S  NaN   NaN   
1240      0      1                2625   8.5167   NaN        C   16   NaN   
427       1      1              250649  14.5000   NaN        S    4   NaN   
1111      1      1  SOTON/O.Q. 3101315  13.7750   NaN        S  NaN   NaN   
657       2      1                2666  19.2583   NaN        C    C   NaN   
658       2      1                2666  19.2583   NaN        C    C   NaN   
359       0      2              248738  29.0000   NaN        S   13   NaN   
611       0      1              392091   9.3500   NaN        S   11   NaN   
548       1      1               29106  18.7500   NaN        S    4   NaN   

                              home.dest  
763          Devon, England Wichita, KS  
747                         Stanton, IA  
1240                                NaN  
427                         Detroit, MI  
1111                                NaN  
657                  Syria New York, NY  
658                  Syria New York, NY  
359   Bangkok, Thailand / Roseville, IL  
611         London, England Norfolk, VA  
548                Cornwall / Akron, OH